spring.application.name=Kario

# MYSQL Configuration
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HIBERNATE Configuration
spring.jpa.hibernate.ddl-auto=update

# MONGO Configuration
spring.data.mongodb.uri=${MONGO_URL}
spring.data.mongodb.username=${MONGO_USER}
spring.data.mongodb.password=${MONGO_PASSWORD}


#* LOCAL VARIABLES >>>>>
SECRET_KEY=${JWT_KEY}
ADMIN_EMAIL=${admin_email}
ADMIN_PASSWORD=${admin_password}
#* <<<<<<<<<<<<<<<<<<<<


# todo H2 Database para tests ------------------
# spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.show-sql=true
# todo -------------------------------------------


logging.level.org.springframework.security=DEBUG
